name: Run Selenium and Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Playwright Browsers
      run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"

    - name: Run tests
      run: mvn clean test

    - name: Archive Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-reports
        path: test-output/
